export type TUserDetail = {
	name: string | null;
	id: number;
	username: string | null;
	avatar: string | null;
	password: boolean;
	phone: string | null;
	email: string | null;
	status: number;
	age: number;
	sex: number;
	qg: number;
	job: string | null;
	path: string | null;
	birthday: string | null;
	desc: string | null;
	token: string | null;
}

export type TloginInfo = {
	userId: string
	password: string
}
export type IToken = {
	token: string
}