// Code generated by goctl. DO NOT EDIT.
// Source: display.proto

package server

import (
	"context"

	"qywk-server/apps/display/rpc/display"
	"qywk-server/apps/display/rpc/internal/logic/plants"
	"qywk-server/apps/display/rpc/internal/svc"
)

type PlantsServer struct {
	svcCtx *svc.ServiceContext
	display.UnimplementedPlantsServer
}

func NewPlantsServer(svcCtx *svc.ServiceContext) *PlantsServer {
	return &PlantsServer{
		svcCtx: svcCtx,
	}
}

func (s *PlantsServer) QueryAll(ctx context.Context, in *display.QueryPlantsReq) (*display.PlantsResp, error) {
	l := plantslogic.NewQueryAllLogic(ctx, s.svcCtx)
	return l.QueryAll(in)
}

func (s *PlantsServer) QueryHas(ctx context.Context, in *display.QueryPlantsReq) (*display.PlantsResp, error) {
	l := plantslogic.NewQueryHasLogic(ctx, s.svcCtx)
	return l.QueryHas(in)
}

func (s *PlantsServer) QueryNotHas(ctx context.Context, in *display.QueryPlantsReq) (*display.PlantsResp, error) {
	l := plantslogic.NewQueryNotHasLogic(ctx, s.svcCtx)
	return l.QueryNotHas(in)
}
