// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.19.4
// source: display.proto

package display

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryPlantsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Page   int32  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size   int32  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *QueryPlantsReq) Reset() {
	*x = QueryPlantsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_display_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryPlantsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPlantsReq) ProtoMessage() {}

func (x *QueryPlantsReq) ProtoReflect() protoreflect.Message {
	mi := &file_display_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPlantsReq.ProtoReflect.Descriptor instead.
func (*QueryPlantsReq) Descriptor() ([]byte, []int) {
	return file_display_proto_rawDescGZIP(), []int{0}
}

func (x *QueryPlantsReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *QueryPlantsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *QueryPlantsReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type Plants struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Tag  []string `protobuf:"bytes,4,rep,name=tag,proto3" json:"tag,omitempty"`
	Desc string   `protobuf:"bytes,5,opt,name=desc,proto3" json:"desc,omitempty"`
	Has  string   `protobuf:"bytes,6,opt,name=has,proto3" json:"has,omitempty"`
}

func (x *Plants) Reset() {
	*x = Plants{}
	if protoimpl.UnsafeEnabled {
		mi := &file_display_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Plants) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plants) ProtoMessage() {}

func (x *Plants) ProtoReflect() protoreflect.Message {
	mi := &file_display_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plants.ProtoReflect.Descriptor instead.
func (*Plants) Descriptor() ([]byte, []int) {
	return file_display_proto_rawDescGZIP(), []int{1}
}

func (x *Plants) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Plants) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Plants) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Plants) GetTag() []string {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *Plants) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Plants) GetHas() string {
	if x != nil {
		return x.Has
	}
	return ""
}

type PlantsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total   int32     `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Records []*Plants `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
}

func (x *PlantsResp) Reset() {
	*x = PlantsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_display_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlantsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlantsResp) ProtoMessage() {}

func (x *PlantsResp) ProtoReflect() protoreflect.Message {
	mi := &file_display_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlantsResp.ProtoReflect.Descriptor instead.
func (*PlantsResp) Descriptor() ([]byte, []int) {
	return file_display_proto_rawDescGZIP(), []int{2}
}

func (x *PlantsResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PlantsResp) GetRecords() []*Plants {
	if x != nil {
		return x.Records
	}
	return nil
}

type Subarea struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url  string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *Subarea) Reset() {
	*x = Subarea{}
	if protoimpl.UnsafeEnabled {
		mi := &file_display_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Subarea) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subarea) ProtoMessage() {}

func (x *Subarea) ProtoReflect() protoreflect.Message {
	mi := &file_display_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subarea.ProtoReflect.Descriptor instead.
func (*Subarea) Descriptor() ([]byte, []int) {
	return file_display_proto_rawDescGZIP(), []int{3}
}

func (x *Subarea) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Subarea) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type QuerySubareaResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subareas []*Subarea `protobuf:"bytes,1,rep,name=subareas,proto3" json:"subareas,omitempty"`
}

func (x *QuerySubareaResp) Reset() {
	*x = QuerySubareaResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_display_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuerySubareaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySubareaResp) ProtoMessage() {}

func (x *QuerySubareaResp) ProtoReflect() protoreflect.Message {
	mi := &file_display_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySubareaResp.ProtoReflect.Descriptor instead.
func (*QuerySubareaResp) Descriptor() ([]byte, []int) {
	return file_display_proto_rawDescGZIP(), []int{4}
}

func (x *QuerySubareaResp) GetSubareas() []*Subarea {
	if x != nil {
		return x.Subareas
	}
	return nil
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_display_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_display_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_display_proto_rawDescGZIP(), []int{5}
}

type QueryMealReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page    int32  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size    int32  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Subarea string `protobuf:"bytes,3,opt,name=subarea,proto3" json:"subarea,omitempty"`
	UserId  string `protobuf:"bytes,4,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *QueryMealReq) Reset() {
	*x = QueryMealReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_display_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryMealReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMealReq) ProtoMessage() {}

func (x *QueryMealReq) ProtoReflect() protoreflect.Message {
	mi := &file_display_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMealReq.ProtoReflect.Descriptor instead.
func (*QueryMealReq) Descriptor() ([]byte, []int) {
	return file_display_proto_rawDescGZIP(), []int{6}
}

func (x *QueryMealReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *QueryMealReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *QueryMealReq) GetSubarea() string {
	if x != nil {
		return x.Subarea
	}
	return ""
}

func (x *QueryMealReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type Meal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subarea    string   `protobuf:"bytes,1,opt,name=subarea,proto3" json:"subarea,omitempty"`
	SubareaUrl string   `protobuf:"bytes,2,opt,name=subareaUrl,proto3" json:"subareaUrl,omitempty"`
	Name       string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Photos     []string `protobuf:"bytes,4,rep,name=photos,proto3" json:"photos,omitempty"`
	Desc       string   `protobuf:"bytes,5,opt,name=desc,proto3" json:"desc,omitempty"`
	Collect    bool     `protobuf:"varint,6,opt,name=collect,proto3" json:"collect,omitempty"`
	Subtitle   []string `protobuf:"bytes,7,rep,name=subtitle,proto3" json:"subtitle,omitempty"`
}

func (x *Meal) Reset() {
	*x = Meal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_display_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Meal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meal) ProtoMessage() {}

func (x *Meal) ProtoReflect() protoreflect.Message {
	mi := &file_display_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meal.ProtoReflect.Descriptor instead.
func (*Meal) Descriptor() ([]byte, []int) {
	return file_display_proto_rawDescGZIP(), []int{7}
}

func (x *Meal) GetSubarea() string {
	if x != nil {
		return x.Subarea
	}
	return ""
}

func (x *Meal) GetSubareaUrl() string {
	if x != nil {
		return x.SubareaUrl
	}
	return ""
}

func (x *Meal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Meal) GetPhotos() []string {
	if x != nil {
		return x.Photos
	}
	return nil
}

func (x *Meal) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Meal) GetCollect() bool {
	if x != nil {
		return x.Collect
	}
	return false
}

func (x *Meal) GetSubtitle() []string {
	if x != nil {
		return x.Subtitle
	}
	return nil
}

type QueryMealResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Meals []*Meal `protobuf:"bytes,1,rep,name=meals,proto3" json:"meals,omitempty"`
}

func (x *QueryMealResp) Reset() {
	*x = QueryMealResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_display_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryMealResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMealResp) ProtoMessage() {}

func (x *QueryMealResp) ProtoReflect() protoreflect.Message {
	mi := &file_display_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMealResp.ProtoReflect.Descriptor instead.
func (*QueryMealResp) Descriptor() ([]byte, []int) {
	return file_display_proto_rawDescGZIP(), []int{8}
}

func (x *QueryMealResp) GetMeals() []*Meal {
	if x != nil {
		return x.Meals
	}
	return nil
}

var File_display_proto protoreflect.FileDescriptor

var file_display_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x22, 0x50, 0x0a, 0x0e, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x76, 0x0a, 0x06, 0x50, 0x6c,
	0x61, 0x6e, 0x74, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61,
	0x67, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x65, 0x73, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63,
	0x12, 0x10, 0x0a, 0x03, 0x68, 0x61, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x68,
	0x61, 0x73, 0x22, 0x4d, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x29, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61,
	0x79, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x73, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x73, 0x22, 0x2f, 0x0a, 0x07, 0x53, 0x75, 0x62, 0x61, 0x72, 0x65, 0x61, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x72, 0x6c, 0x22, 0x40, 0x0a, 0x10, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x75, 0x62, 0x61, 0x72,
	0x65, 0x61, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2c, 0x0a, 0x08, 0x73, 0x75, 0x62, 0x61, 0x72, 0x65,
	0x61, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x64, 0x69, 0x73, 0x70, 0x6c,
	0x61, 0x79, 0x2e, 0x53, 0x75, 0x62, 0x61, 0x72, 0x65, 0x61, 0x52, 0x08, 0x73, 0x75, 0x62, 0x61,
	0x72, 0x65, 0x61, 0x73, 0x22, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x68, 0x0a, 0x0c, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4d, 0x65, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x61, 0x72,
	0x65, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x61, 0x72, 0x65,
	0x61, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0xb6, 0x01, 0x0a, 0x04, 0x4d, 0x65,
	0x61, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x61, 0x72, 0x65, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x61, 0x72, 0x65, 0x61, 0x12, 0x1e, 0x0a, 0x0a,
	0x73, 0x75, 0x62, 0x61, 0x72, 0x65, 0x61, 0x55, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x73, 0x75, 0x62, 0x61, 0x72, 0x65, 0x61, 0x55, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x06, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x63,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x75, 0x62, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x73, 0x75, 0x62, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x22, 0x34, 0x0a, 0x0d, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4d, 0x65, 0x61, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x23, 0x0a, 0x05, 0x6d, 0x65, 0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x4d, 0x65, 0x61,
	0x6c, 0x52, 0x05, 0x6d, 0x65, 0x61, 0x6c, 0x73, 0x32, 0xb9, 0x01, 0x0a, 0x06, 0x70, 0x6c, 0x61,
	0x6e, 0x74, 0x73, 0x12, 0x38, 0x0a, 0x08, 0x71, 0x75, 0x65, 0x72, 0x79, 0x41, 0x6c, 0x6c, 0x12,
	0x17, 0x2e, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50,
	0x6c, 0x61, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x64, 0x69, 0x73, 0x70, 0x6c,
	0x61, 0x79, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x38, 0x0a,
	0x08, 0x71, 0x75, 0x65, 0x72, 0x79, 0x48, 0x61, 0x73, 0x12, 0x17, 0x2e, 0x64, 0x69, 0x73, 0x70,
	0x6c, 0x61, 0x79, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x1a, 0x13, 0x2e, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x50, 0x6c, 0x61,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3b, 0x0a, 0x0b, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x4e, 0x6f, 0x74, 0x48, 0x61, 0x73, 0x12, 0x17, 0x2e, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79,
	0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x1a,
	0x13, 0x2e, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x32, 0x7f, 0x0a, 0x04, 0x6d, 0x65, 0x61, 0x6c, 0x12, 0x3b, 0x0a, 0x0c,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x53, 0x75, 0x62, 0x61, 0x72, 0x65, 0x61, 0x12, 0x10, 0x2e, 0x64,
	0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19,
	0x2e, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x75,
	0x62, 0x61, 0x72, 0x65, 0x61, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3a, 0x0a, 0x09, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x4d, 0x65, 0x61, 0x6c, 0x12, 0x15, 0x2e, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79,
	0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4d, 0x65, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e,
	0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4d, 0x65, 0x61,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x64, 0x69, 0x73, 0x70, 0x6c,
	0x61, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_display_proto_rawDescOnce sync.Once
	file_display_proto_rawDescData = file_display_proto_rawDesc
)

func file_display_proto_rawDescGZIP() []byte {
	file_display_proto_rawDescOnce.Do(func() {
		file_display_proto_rawDescData = protoimpl.X.CompressGZIP(file_display_proto_rawDescData)
	})
	return file_display_proto_rawDescData
}

var file_display_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_display_proto_goTypes = []any{
	(*QueryPlantsReq)(nil),   // 0: display.QueryPlantsReq
	(*Plants)(nil),           // 1: display.Plants
	(*PlantsResp)(nil),       // 2: display.PlantsResp
	(*Subarea)(nil),          // 3: display.Subarea
	(*QuerySubareaResp)(nil), // 4: display.QuerySubareaResp
	(*Request)(nil),          // 5: display.Request
	(*QueryMealReq)(nil),     // 6: display.QueryMealReq
	(*Meal)(nil),             // 7: display.Meal
	(*QueryMealResp)(nil),    // 8: display.QueryMealResp
}
var file_display_proto_depIdxs = []int32{
	1, // 0: display.PlantsResp.records:type_name -> display.Plants
	3, // 1: display.QuerySubareaResp.subareas:type_name -> display.Subarea
	7, // 2: display.QueryMealResp.meals:type_name -> display.Meal
	0, // 3: display.plants.queryAll:input_type -> display.QueryPlantsReq
	0, // 4: display.plants.queryHas:input_type -> display.QueryPlantsReq
	0, // 5: display.plants.queryNotHas:input_type -> display.QueryPlantsReq
	5, // 6: display.meal.querySubarea:input_type -> display.Request
	6, // 7: display.meal.queryMeal:input_type -> display.QueryMealReq
	2, // 8: display.plants.queryAll:output_type -> display.PlantsResp
	2, // 9: display.plants.queryHas:output_type -> display.PlantsResp
	2, // 10: display.plants.queryNotHas:output_type -> display.PlantsResp
	4, // 11: display.meal.querySubarea:output_type -> display.QuerySubareaResp
	8, // 12: display.meal.queryMeal:output_type -> display.QueryMealResp
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_display_proto_init() }
func file_display_proto_init() {
	if File_display_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_display_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*QueryPlantsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_display_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Plants); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_display_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*PlantsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_display_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Subarea); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_display_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*QuerySubareaResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_display_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_display_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*QueryMealReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_display_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*Meal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_display_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*QueryMealResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_display_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_display_proto_goTypes,
		DependencyIndexes: file_display_proto_depIdxs,
		MessageInfos:      file_display_proto_msgTypes,
	}.Build()
	File_display_proto = out.File
	file_display_proto_rawDesc = nil
	file_display_proto_goTypes = nil
	file_display_proto_depIdxs = nil
}
