// Code generated by goctl. DO NOT EDIT.
// Source: display.proto

package server

import (
	"context"

	"qywk-server/apps/display/rpc/display"
	"qywk-server/apps/display/rpc/internal/logic/meal"
	"qywk-server/apps/display/rpc/internal/svc"
)

type MealServer struct {
	svcCtx *svc.ServiceContext
	display.UnimplementedMealServer
}

func NewMealServer(svcCtx *svc.ServiceContext) *MealServer {
	return &MealServer{
		svcCtx: svcCtx,
	}
}

func (s *MealServer) QuerySubarea(ctx context.Context, in *display.Request) (*display.QuerySubareaResp, error) {
	l := meallogic.NewQuerySubareaLogic(ctx, s.svcCtx)
	return l.QuerySubarea(in)
}

func (s *MealServer) QueryMeal(ctx context.Context, in *display.QueryMealReq) (*display.QueryMealResp, error) {
	l := meallogic.NewQueryMealLogic(ctx, s.svcCtx)
	return l.QueryMeal(in)
}
