// Code generated by goctl. DO NOT EDIT.
package types

type Plants struct {
	Id   string   `json:"id"`
	Name string   `json:"name"`
	Url  string   `json:"url"`
	Tag  []string `json:"tag"`
	Desc string   `json:"desc"`
	Has  string   `json:"has"`
}

type QueryPlantsReq struct {
	UserId string `json:"userId"`
	Page   int32  `json:"page"`
	Size   int32  `json:"size"`
}

type Result struct {
}
