// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"qywk-server/apps/user/rpc/internal/logic/info"
	"qywk-server/apps/user/rpc/internal/svc"
	"qywk-server/apps/user/rpc/user"
)

type InfoServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedInfoServer
}

func NewInfoServer(svcCtx *svc.ServiceContext) *InfoServer {
	return &InfoServer{
		svcCtx: svcCtx,
	}
}

// 查询用户的基本信息
func (s *InfoServer) GetUserInfoBasic(ctx context.Context, in *user.UserInfoBasicReq) (*user.UserInfoBasicResp, error) {
	l := infologic.NewGetUserInfoBasicLogic(ctx, s.svcCtx)
	return l.GetUserInfoBasic(in)
}

// 查询用户的详细信息
func (s *InfoServer) GetUserInfoDetail(ctx context.Context, in *user.UserInfoDetailReq) (*user.UserInfoDetailResp, error) {
	l := infologic.NewGetUserInfoDetailLogic(ctx, s.svcCtx)
	return l.GetUserInfoDetail(in)
}
