// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package login

import (
	"context"

	"qywk-server/apps/user/rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ChangeReq          = user.ChangeReq
	ChangeResp         = user.ChangeResp
	CodeReq            = user.CodeReq
	CodeResp           = user.CodeResp
	ForgetReq          = user.ForgetReq
	ForgetResp         = user.ForgetResp
	LoginReq           = user.LoginReq
	LoginResp          = user.LoginResp
	RegisterReq        = user.RegisterReq
	RegisterResp       = user.RegisterResp
	UserInfoBasicReq   = user.UserInfoBasicReq
	UserInfoBasicResp  = user.UserInfoBasicResp
	UserInfoDetailReq  = user.UserInfoDetailReq
	UserInfoDetailResp = user.UserInfoDetailResp
	WechatLoginReq     = user.WechatLoginReq

	Login interface {
		// 普通登陆
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		// 微信快速登陆
		WechatLogin(ctx context.Context, in *WechatLoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		// 邮箱号注册
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
		// 发送验证码
		SentCode(ctx context.Context, in *CodeReq, opts ...grpc.CallOption) (*CodeResp, error)
		// 修改密码
		Change(ctx context.Context, in *ChangeReq, opts ...grpc.CallOption) (*ChangeResp, error)
		// 忘记密码
		Forget(ctx context.Context, in *ForgetReq, opts ...grpc.CallOption) (*ForgetResp, error)
	}

	defaultLogin struct {
		cli zrpc.Client
	}
)

func NewLogin(cli zrpc.Client) Login {
	return &defaultLogin{
		cli: cli,
	}
}

// 普通登陆
func (m *defaultLogin) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := user.NewLoginClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

// 微信快速登陆
func (m *defaultLogin) WechatLogin(ctx context.Context, in *WechatLoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := user.NewLoginClient(m.cli.Conn())
	return client.WechatLogin(ctx, in, opts...)
}

// 邮箱号注册
func (m *defaultLogin) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	client := user.NewLoginClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

// 发送验证码
func (m *defaultLogin) SentCode(ctx context.Context, in *CodeReq, opts ...grpc.CallOption) (*CodeResp, error) {
	client := user.NewLoginClient(m.cli.Conn())
	return client.SentCode(ctx, in, opts...)
}

// 修改密码
func (m *defaultLogin) Change(ctx context.Context, in *ChangeReq, opts ...grpc.CallOption) (*ChangeResp, error) {
	client := user.NewLoginClient(m.cli.Conn())
	return client.Change(ctx, in, opts...)
}

// 忘记密码
func (m *defaultLogin) Forget(ctx context.Context, in *ForgetReq, opts ...grpc.CallOption) (*ForgetResp, error) {
	client := user.NewLoginClient(m.cli.Conn())
	return client.Forget(ctx, in, opts...)
}
