// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	plants "qywk-server/apps/display/api/internal/handler/plants"
	"qywk-server/apps/display/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 查询全部中药植物信息
				Method:  http.MethodPost,
				Path:    "/query/all",
				Handler: plants.QueryAllHandler(serverCtx),
			},
			{
				// 查询已拥有的中药植物信息
				Method:  http.MethodPost,
				Path:    "/query/has",
				Handler: plants.QueryHasHandler(serverCtx),
			},
			{
				// 查询未拥有的中药植物信息
				Method:  http.MethodGet,
				Path:    "/query/notHas",
				Handler: plants.QueryNotHasHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Jwt.AccessSecret),
		rest.WithPrefix("/display/plants"),
	)
}
