// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package info

import (
	"context"

	"qywk-server/apps/user/rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ChangeReq          = user.ChangeReq
	ChangeResp         = user.ChangeResp
	CodeReq            = user.CodeReq
	CodeResp           = user.CodeResp
	ForgetReq          = user.ForgetReq
	ForgetResp         = user.ForgetResp
	LoginReq           = user.LoginReq
	LoginResp          = user.LoginResp
	RegisterReq        = user.RegisterReq
	RegisterResp       = user.RegisterResp
	UserInfoBasicReq   = user.UserInfoBasicReq
	UserInfoBasicResp  = user.UserInfoBasicResp
	UserInfoDetailReq  = user.UserInfoDetailReq
	UserInfoDetailResp = user.UserInfoDetailResp
	WechatLoginReq     = user.WechatLoginReq

	Info interface {
		// 查询用户的基本信息
		GetUserInfoBasic(ctx context.Context, in *UserInfoBasicReq, opts ...grpc.CallOption) (*UserInfoBasicResp, error)
		// 查询用户的详细信息
		GetUserInfoDetail(ctx context.Context, in *UserInfoDetailReq, opts ...grpc.CallOption) (*UserInfoDetailResp, error)
	}

	defaultInfo struct {
		cli zrpc.Client
	}
)

func NewInfo(cli zrpc.Client) Info {
	return &defaultInfo{
		cli: cli,
	}
}

// 查询用户的基本信息
func (m *defaultInfo) GetUserInfoBasic(ctx context.Context, in *UserInfoBasicReq, opts ...grpc.CallOption) (*UserInfoBasicResp, error) {
	client := user.NewInfoClient(m.cli.Conn())
	return client.GetUserInfoBasic(ctx, in, opts...)
}

// 查询用户的详细信息
func (m *defaultInfo) GetUserInfoDetail(ctx context.Context, in *UserInfoDetailReq, opts ...grpc.CallOption) (*UserInfoDetailResp, error) {
	client := user.NewInfoClient(m.cli.Conn())
	return client.GetUserInfoDetail(ctx, in, opts...)
}
