// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	login "qywk-server/apps/user/api/internal/handler/login"
	"qywk-server/apps/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 修改密码
				Method:  http.MethodPost,
				Path:    "/change",
				Handler: login.ChangeHandler(serverCtx),
			},
			{
				// 微信快速登陆
				Method:  http.MethodPost,
				Path:    "/fast",
				Handler: login.FastHandler(serverCtx),
			},
			{
				// 忘记密码
				Method:  http.MethodPost,
				Path:    "/forget",
				Handler: login.ForgetHandler(serverCtx),
			},
			{
				// 普通登陆
				Method:  http.MethodPost,
				Path:    "/normal",
				Handler: login.LoginHandler(serverCtx),
			},
			{
				// 手机号注册
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: login.RegisterHandler(serverCtx),
			},
			{
				// 发送验证码
				Method:  http.MethodPost,
				Path:    "/sent/code",
				Handler: login.SentCodeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/user/login"),
	)
}
