// Code generated by goctl. DO NOT EDIT.
package types

type ChangeReq struct {
	UserId      string `json:"userId"`
	Password    string `json:"password"`
	Tel         string `json:"tel"`
	Code        string `json:"code"`
	NewPassword string `json:"newPassword"`
}

type CodeReq struct {
	Tel string `json:"tel"`
}

type ForgetRep struct {
	UserId   string `json:"userId"`
	Password string `json:"password"`
	Tel      string `json:"tel"`
	Code     string `json:"code"`
}

type LoginReq struct {
	UserId   string `json:"userId"`
	Password string `json:"password"`
}

type RegisterReq struct {
	Password string `json:"password"`
	Code     string `json:"code"`
	Tel      string `json:"tel"`
	Nickname string `json:"nickname"`
}

type Result struct {
}

type WechatLoginReq struct {
	Code string `json:"code"`
}
